spring:
  jpa:
    # Configuration JPA commune a tous les profils (h2, postgres).
    # Les differents profils peuvent surcharger ponctuellement si necessaire.
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false


