spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/potify
    username: postgres
    password: "123456"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:nizarakka07@gmail.com}
    password: ${MAIL_PASSWORD:phfakngqcxibdghc}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

application:
  security:
    jwt:
      # Secret key (HS512 requires 64 bytes)
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      # 1 day in milliseconds
      expiration: 86400000
      refresh-token:
        # 7 days in milliseconds
        expiration: 604800000
