spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/potify
    username: postgres
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:nizarakka07@gmail.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

application:
  security:
    jwt:
      # Secret key (HS512 requires 64 bytes)
      secret-key: ${JWT_SECRET_KEY:}
      # 1 day in milliseconds
      expiration: 86400000
      refresh-token:
        # 7 days in milliseconds
        expiration: 604800000
    google:
      client-id: ${GOOGLE_CLIENT_ID:1077945200760-tbqpb374p6uciqsubi9v1l2tsbv8drd7.apps.googleusercontent.com}
      client-secret: ${GOOGLE_CLIENT_SECRET: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}

