spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://localhost:5432/potify
    username: postgres
    password: "123456"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.block.ms: 2000

server:
  port: 8083

stripe:
  api:
    key: ${STRIPE_API_KEY:sk_test_51SezNMLcOzCMO02ZyUV8xpTzxVtaVcq0Xr2mL3OdN2zWlLUshYifyTAvPuBF4LNfHmEpUeAlMjB40sj9FS0PLkRE00PxQ5kDtj}
  frontend-url: ${FRONTEND_URL:http://localhost:9000}

paypal:
  client-id: ${PAYPAL_CLIENT_ID:AeguYpyNk0WMR5IzqJ8XlJiaK0cpK8Ko3XePRRlTBvag945B8XVg2nQO5tWlky9K975vmIbMAMQFmlpd}
  client-secret: ${PAYPAL_CLIENT_SECRET:EJrTmR7jth77I_jgnqDeDfeZN5lnuZ8ylaifZLCvEsh4NGkW3SCN3Nr4J40N04I2i8jYy1kZ0nuKlL7w}
  mode: ${PAYPAL_MODE:sandbox}
  api-url: ${PAYPAL_API_URL:https://api-m.sandbox.paypal.com} # URL de l'API de test PayPal

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
