spring:
  application:
    name: pool
  datasource:
    url: jdbc:postgresql://localhost:5432/potify
    username: postgres
    password: "123456"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:nizarakka07@gmail.com}
    password: ${MAIL_PASSWORD:prjjnvfjsjyucddn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.block.ms: 2000

server:
  port: 8082

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
  cloudinary:
    cloud-name: dsoliwbee
    api-key: "628423652634248"
    api-secret: wL8TV51jdidtGpCP7ibcn4pFgNA
  ai:
    gemini:
      api-key: AIzaSyA4GiqGfc56ZqG2ObiQ5htbsDmscCRJr7E

